FROM debian:stable-slim

ARG USERNAME=dev
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create user "$USERNAME"
RUN apt-get update && apt-get install -y sudo ssh zsh git curl  \
  && useradd -m -s /bin/zsh $USERNAME                           \
  && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers    \
  && apt-get clean                                              \
  && rm -rf /var/lib/apt/lists/*

USER $USERNAME

# Install chezmoi & dotfiles
RUN cd                      \
  && mkdir -p .local/bin    \
  && GIT_EMAIL=changeme sh -c "$(curl -fsLS get.chezmoi.io/lb)" -- init --apply https://github.com/nicolascochin/dotfiles.git

