FROM debian:stable-slim

ARG USERNAME=dev
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create user "$USERNAME"
RUN apt-get update && apt-get install -y sudo ssh zsh git curl  \
  && useradd -m -s /bin/zsh $USERNAME                           \
  && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers    \
  && apt-get clean                                              \
  && rm -rf /var/lib/apt/lists/*

USER $USERNAME

ENV HOME=/home/$USERNAME
ENV NVM_DIR=$HOME/.nvm

RUN curl -fsSLq https://github.com/nvm-sh/nvm/raw/HEAD/install.sh | bash \
  && . $NVM_DIR/nvm.sh && nvm install --lts \
  && curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash 

ARG CACHEBUST=1
# Install chezmoi & dotfiles
RUN cd                      \
  && mkdir -p .local/bin    \
  && GIT_EMAIL=changeme sh -c "$(curl -fsLS get.chezmoi.io/lb)" -- init --apply https://github.com/nicolascochin/dotfiles.git

