name: Build and Push All Dockerfiles

on:
  push:
    branches:
      - main

  schedule:
     - cron: '0 6 * * 1'  # Chaque lundi à 06:00 UTC

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Find Dockerfiles
        id: dockerfiles
        run: |
          files=$(find . -maxdepth 1 -type f -name 'Dockerfile-*' | sed 's|./||')
          echo "Found files:"
          echo "$files"
          echo "dockerfiles=$(echo "$files" | paste -sd "," -)" >> "$GITHUB_OUTPUT"

      - name: Build and push all images
        run: |
          IFS=',' read -ra files <<< "${{ steps.dockerfiles.outputs.dockerfiles }}"
          for file in "${files[@]}"; do
            suffix=${file#Dockerfile-}
            echo "→ Building $file as nicochin/dev-images:$suffix-latest"
            docker build -f "$file" -t "nicochin/dev-images:$suffix-latest" .
            docker push "nicochin/dev-images:$suffix-latest"
          done
